dist: bionic
sudo: required

jobs:
  include:
    - stage: Lint
      language: cpp
      addons:
        apt:
          packages:
            - clang-format
      script:
        - find . -regex '.*\.\(hh?\|cc?\|hpp\|cpp\)$' | xargs clang-format -i -style=file
        - git diff --exit-code
    - stage: build baseboxd from source in docker container
      language: bash
      services:
        - docker
      script:
        - cd docker/from_source
        - docker build .
